### ISSUE TITLE
NPE on copying empty DDSketch

### ISSUE THREAD

**Issue by IgorPerikov** [DataDog/sketches-java#10]
**Describe what happened:**
Copying empty DDSketch crashes with NPE:

```
Exception in thread "main" java.lang.NullPointerException
	at com.datadoghq.sketch.ddsketch.store.DenseStore.<init>(DenseStore.java:50)
	at com.datadoghq.sketch.ddsketch.store.UnboundedSizeDenseStore.<init>(UnboundedSizeDenseStore.java:23)
	at com.datadoghq.sketch.ddsketch.store.UnboundedSizeDenseStore.copy(UnboundedSizeDenseStore.java:67)
	at com.datadoghq.sketch.ddsketch.DDSketch.<init>(DDSketch.java:110)
	at com.datadoghq.sketch.ddsketch.DDSketch.copy(DDSketch.java:186)
```

**Describe what you expected:**
Successfully get a copy of empty Sketch

**Steps to reproduce the issue:**
```java
DDSketch ddSketch = DDSketch.memoryOptimal(0.05);
ddSketch.copy();
```

Although use case is a bit rare and kinda useless, it's a valid one and throwing exceptions seems urneasonable here, not something what I would call the best practice for an API design

**Comment by CharlesMasson** [comment]
That shouldn't happen indeed. Thanks for reporting.

**Comment by IgorPerikov** [comment]
Thanks for the quick reaction
